version: 2
jobs:
  build:
    docker:
      - image: qrledger/qrl-docker:noble
    steps:
      - checkout
      - run: cmake .
      - run: make

workflows:
  version: 2
  build_all:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
