version: 2
jobs:
  build:
    docker:
      - image: qrledger/qrl-docker-ci:noble
    steps:
      - checkout
      - run: sudo apt-get install libssl-dev
      # TODO: openssl into docker ci helper
      - run: cmake . -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF -DMICROHTTPD_ENABLE=OFF
      - run: make

workflows:
  version: 2
  build_all:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
